createCard('Programação', 'O que é JavaScript?', 'O JavaScript é uma linguagem de programação muito usada frequentemente na criação de websites')
createCard('Geografia', 'Qual a capital da França?', 'A capital da França é Paris')
createCard('Programação', 'O que é CSS?', 'O CSS é uma linguagem de estilização voltada para a criação de websites')
createCard('Programação', 'O que é uma function?', 'Uma function é um bloco onde tarefas serão executadas e um valor será retornado')
createCard('Programação', 'O que é Phyton', 'Phyton é uma linguagem de programação muito popular associada ao uso em automatizações e Inteligencia Arificial')
createCard('Lingua Inglesa', 'Qual o significado da palara <i>QUEUE</i>?', 'A palavra <i>QUEUE</i> significa FILA')
createCard('Lingua Inglesa', 'Qual é a palavra para CHATEADO em inglês?', 'A palavra para CHATEADO, em inglês, é <i>UPSET</i>')
createCard('Geografia', 'Qual país desbancou a China recentemente e tomou o posto de país mais populoso do mundo?', 'O país que utrapassou a China em população foi a India, se tornando atualmento o país mais populoso do mundo')
createCard('Geografia', 'Há quantos países no continente sul-americano?', 'A America do Sul possui 12 países mais a Guiana Francesa, um território ultramarinoS da França')